# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=140, null=True, verbose_name='имя')),
            ],
            options={
                'verbose_name_plural': 'Города',
                'verbose_name': 'Город',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(default=0, verbose_name='позиция')),
                ('show', models.BooleanField(default=True, verbose_name='отображать')),
                ('name', models.CharField(blank=True, max_length=140, null=True, verbose_name='имя')),
                ('url', models.CharField(blank=True, max_length=250, null=True, verbose_name='ссылка')),
                ('antey', models.BooleanField(default=False, verbose_name='алмаз-антей')),
                ('city', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='partners.City')),
            ],
            options={
                'verbose_name_plural': 'Партнёры',
                'verbose_name': 'Партнёр',
                'ordering': ['pos'],
            },
        ),
    ]
